# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-26 12:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalCreator',
            fields=[
                ('journalID', models.AutoField(primary_key=True, serialize=False)),
                ('journal_name', models.CharField(max_length=50, unique=True)),
                ('student', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
