# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-20 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import log.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_saved', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(max_length=9999, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('quizID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.IntegerField(default=0)),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_email', models.EmailField(max_length=70, unique=True)),
                ('journalID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lecturer_email', models.EmailField(max_length=70, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=9999, null=True)),
                ('tag', models.CharField(max_length=25)),
                ('lecturer_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Subject')),
                ('quizID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoID', models.URLField(unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.ForeignKey(on_delete=log.models.Student, to='log.Subject'),
        ),
        migrations.AddField(
            model_name='upload',
            name='videoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Video'),
        ),
        migrations.AddField(
            model_name='quizresults',
            name='studentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Student'),
        ),
        migrations.AddField(
            model_name='journal',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Student'),
        ),
        migrations.AddField(
            model_name='journal',
            name='videoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Video'),
        ),
        migrations.AddField(
            model_name='forum',
            name='author_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Student'),
        ),
        migrations.AddField(
            model_name='forum',
            name='videoID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Video'),
        ),
    ]
