# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20190801_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='journalID',
        ),
    ]
