# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-28 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_journalcreator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=2000, null=True)),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('user', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Video')),
            ],
        ),
        migrations.CreateModel(
            name='JournalContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_saved', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.CharField(max_length=9999, null=True)),
                ('journalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.JournalCreator')),
                ('videoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Video')),
            ],
        ),
    ]
