# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_remove_journalcontent_journalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
