# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_video_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
    ]
