# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-10 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_subject_dislikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFileUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(null=True, upload_to='student-uploads/', verbose_name='')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(max_length=25)),
                ('comment', models.CharField(max_length=9999, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Subject')),
                ('uploader', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentVideoLinkUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_link', models.URLField(max_length=250)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.CharField(max_length=25)),
                ('comment', models.CharField(max_length=9999, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Subject')),
                ('uploader', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
