# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-11 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_studentfileuploads_studentvideolinkuploads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='studentfileuploads',
            options={'verbose_name_plural': 'Student File Uploads'},
        ),
        migrations.AlterModelOptions(
            name='studentvideolinkuploads',
            options={'verbose_name_plural': 'Student Link Uploads'},
        ),
        migrations.RemoveField(
            model_name='studentfileuploads',
            name='id',
        ),
        migrations.RemoveField(
            model_name='studentvideolinkuploads',
            name='id',
        ),
        migrations.AddField(
            model_name='studentfileuploads',
            name='upload_file_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentvideolinkuploads',
            name='upload_link_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
