# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-11 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_auto_20190811_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='studentfileuploads',
            name='comment',
            field=models.TextField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='first_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.StudentFileUploads'),
        ),
        migrations.AddField(
            model_name='filecomment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='log.FileComment'),
        ),
    ]
