# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-11 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20190811_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='filecomment',
            name='first_post',
        ),
        migrations.RemoveField(
            model_name='filecomment',
            name='reply',
        ),
        migrations.DeleteModel(
            name='FileComment',
        ),
    ]
