# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-11 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20190811_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcontent',
            name='timestamp',
            field=models.CharField(default=0.0, max_length=7),
        ),
    ]
