# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-11 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_auto_20190811_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcontent',
            name='timestamp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
