# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_remove_filecomment_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('first_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.StudentVideoLinkUploads')),
            ],
        ),
    ]
