# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_linkcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteForQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_needing_covered', models.CharField(max_length=250)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.Subject')),
                ('voter', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
