# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0015_voteforquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteforquiz',
            name='videoID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='log.Video'),
            preserve_default=False,
        ),
    ]
